### ISSUE TITLE
Precompiling assets failed on deploy to heroku , please make dockerfile or publish on dockerhub

### ISSUE THREAD

**Issue by kakamband** [jbox-web/deploy-it#2]
-----> Ruby app detected

-----> Installing bundler 2.1.4

-----> Removing BUNDLED WITH version in the Gemfile.lock

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.6.6

-----> Installing dependencies using bundler 2.1.4

       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4

       Fetching gem metadata from https://rails-assets.org/..

       Fetching gem metadata from https://rubygems.org/.........

       Fetching https://github.com/jbox-web/action_form.git

       Fetching https://github.com/jbox-web/active_use_case.git

       Fetching https://github.com/jbox-web/async_model.git

       Fetching https://github.com/jbox-web/async_notifications.git

       Fetching https://github.com/jbox-web/foreman.git

       Fetching gem metadata from https://rails-assets.org/..

       Fetching https://github.com/libgit2/rugged.git

       Submodule 'vendor/libgit2' (https://github.com/libgit2/libgit2.git) registered for path 'vendor/libgit2'

       Cloning into '/tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/bundler/gems/rugged-5807a7e6d234/vendor/libgit2'...

       Fetching rake 13.0.2

       Installing rake 13.0.2

       Fetching concurrent-ruby 1.1.7

       Fetching thread_safe 0.3.6

       Fetching minitest 5.14.2

       Installing minitest 5.14.2

       Installing concurrent-ruby 1.1.7

       Installing thread_safe 0.3.6

       Fetching builder 3.2.4

       Installing builder 3.2.4

       Fetching erubi 1.10.0

       Installing erubi 1.10.0

       Fetching mini_portile2 2.4.0

       Fetching crass 1.0.6

       Installing mini_portile2 2.4.0

       Installing crass 1.0.6

       Fetching rack 2.2.3

       Fetching nio4r 2.5.4

       Installing rack 2.2.3

       Installing nio4r 2.5.4 with native extensions

       Fetching websocket-extensions 0.1.5

       Installing websocket-extensions 0.1.5

       Fetching mini_mime 1.0.2

       Installing mini_mime 1.0.2

       Fetching mimemagic 0.3.5

       Fetching arel 9.0.0

       Installing arel 9.0.0

       Installing mimemagic 0.3.5

       Using bundler 2.1.4

       Fetching method_source 1.0.0

       Installing method_source 1.0.0

       Fetching thor 1.0.1

       Installing thor 1.0.1

       Fetching zeitwerk 2.4.2

       Installing zeitwerk 2.4.2

       Fetching ast 2.4.1

       Installing ast 2.4.1

       Using async_notifications 1.0.0 from https://github.com/jbox-web/async_notifications.git (at 1.0.0@e6e98a3)

       Fetching execjs 2.7.0

       Installing execjs 2.7.0

       Fetching bcrypt 3.1.16

       Installing bcrypt 3.1.16 with native extensions

       Fetching msgpack 1.3.3

       Fetching bootstrap-growl-rails 3.1.3

       Installing msgpack 1.3.3 with native extensions

       Installing bootstrap-growl-rails 3.1.3

       Fetching gem_config 0.3.2

       Installing gem_config 0.3.2

       Fetching ffi 1.14.0

       Installing ffi 1.14.0 with native extensions

       Fetching bootstrap-switch-rails 3.3.5

       Installing bootstrap-switch-rails 3.3.5

       Fetching bootstrap_form 2.7.0

       Installing bootstrap_form 2.7.0

       Fetching chartkick 3.4.2

       Installing chartkick 3.4.2

       Fetching coffee-script-source 1.12.2

       Installing coffee-script-source 1.12.2

       Fetching connection_pool 2.2.3

       Installing connection_pool 2.2.3

       Fetching crummy 1.8.0

       Installing crummy 1.8.0

       Fetching orm_adapter 0.5.0

       Installing orm_adapter 0.5.0

       Fetching excon 0.78.1

       Installing excon 0.78.1

       Fetching multi_json 1.15.0

       Installing multi_json 1.15.0

       Fetching dotenv 2.7.6

       Installing dotenv 2.7.6

       Fetching dry-equalizer 0.3.0

       Installing dry-equalizer 0.3.0

       Fetching dry-inflector 0.2.0

       Installing dry-inflector 0.2.0

       Fetching erubis 2.7.0

       Installing erubis 2.7.0

       Fetching fast_blank 1.0.0

       Installing fast_blank 1.0.0 with native extensions

       Fetching ruby2_keywords 0.0.2

       Installing ruby2_keywords 0.0.2

       Fetching temple 0.8.2

       Installing temple 0.8.2

       Fetching tilt 2.0.10

       Installing tilt 2.0.10

       Fetching sexp_processor 4.15.1

       Installing sexp_processor 4.15.1

       Fetching hashie 4.1.0

       Installing hashie 4.1.0

       Fetching highline 2.0.3

       Installing highline 2.0.3

       Fetching hiredis 0.6.3

       Installing hiredis 0.6.3 with native extensions

       Fetching rainbow 3.0.0

       Installing rainbow 3.0.0

       Fetching unicode-display_width 1.7.0

       Installing unicode-display_width 1.7.0

       Fetching kaminari-core 1.2.1

       Installing kaminari-core 1.2.1

       Fetching libv8 8.4.255.0 (x86_64-linux)

       Fetching logster 2.9.4

       Installing logster 2.9.4

       Fetching mysql2 0.5.3

       Installing mysql2 0.5.3 with native extensions

       Installing libv8 8.4.255.0 (x86_64-linux)

       Fetching nested_form 0.3.2

       Installing nested_form 0.3.2

       Fetching net-ssh 6.1.0

       Installing net-ssh 6.1.0

       Fetching tty-color 0.6.0

       Installing tty-color 0.6.0

       Fetching pg 1.2.3

       Installing pg 1.2.3 with native extensions

       Fetching rails-assets-jquery 3.4.1

       Installing rails-assets-jquery 3.4.1

       Fetching rails-assets-php-date-formatter 1.3.5

       Installing rails-assets-php-date-formatter 1.3.5

       Fetching rails-assets-highstock-release 6.0.3

       Installing rails-assets-highstock-release 6.0.3

       Fetching rdoc 6.2.1

       Installing rdoc 6.2.1

       Fetching redis 4.2.5

       Installing redis 4.2.5

       Using rugged 1.0.0 from https://github.com/libgit2/rugged.git (at v1.0.0@5807a7e)

       Fetching select2-rails 4.0.13

       Installing select2-rails 4.0.13

       Fetching settingslogic 2.0.9

       Installing settingslogic 2.0.9

       Fetching sshkey 2.0.0

       Installing sshkey 2.0.0

       Fetching strings-ansi 0.2.0

       Installing strings-ansi 0.2.0

       Fetching unicode_utils 1.4.0

       Installing unicode_utils 1.4.0

       Fetching symbol-fstring 1.0.0

       Installing symbol-fstring 1.0.0 with native extensions

       /tmp/build_49dc4e5c_/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block

       Fetching syslogger 1.6.5

       Installing syslogger 1.6.5

       Fetching tty-screen 0.8.1

       Installing tty-screen 0.8.1

       Fetching turbolinks-source 5.2.0

       Installing turbolinks-source 5.2.0

       Fetching yajl-ruby 1.4.1

       Installing yajl-ruby 1.4.1 with native extensions

       /tmp/build_49dc4e5c_/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block

       Fetching tzinfo 1.2.9

       Installing tzinfo 1.2.9

       Fetching nokogiri 1.10.10

       Fetching aasm 5.1.1

       Installing aasm 5.1.1

       Installing nokogiri 1.10.10 with native extensions

       Fetching i18n 1.8.5

       Installing i18n 1.8.5

       Fetching dry-core 0.5.0

       Installing dry-core 0.5.0

       Fetching websocket-driver 0.7.3

       Installing websocket-driver 0.7.3 with native extensions

       Fetching rack-test 1.1.0

       Installing rack-test 1.1.0

       Fetching sprockets 4.0.2

       Installing sprockets 4.0.2

       Fetching warden 1.2.9

       Installing warden 1.2.9

       Fetching rack-accept 0.4.5

       Installing rack-accept 0.4.5

       Fetching rack-mini-profiler 2.2.0

       Installing rack-mini-profiler 2.2.0

       Fetching mail 2.7.1

       Fetching marcel 0.3.3

       Installing marcel 0.3.3

       Fetching figaro 1.2.0

       Installing mail 2.7.1

       Installing figaro 1.2.0

       Fetching parser 2.7.2.0

       Installing parser 2.7.2.0

       Fetching autoprefixer-rails 10.1.0.0

       Installing autoprefixer-rails 10.1.0.0

       Fetching uglifier 4.2.0

       Installing uglifier 4.2.0

       Fetching puma 5.1.1

       Fetching bootstrap-navbar 3.1.0

       Installing bootstrap-navbar 3.1.0

       Installing puma 5.1.1 with native extensions

       Fetching coffee-script 2.4.1

       Installing coffee-script 2.4.1

       Fetching docker-api 1.34.2

       Installing docker-api 1.34.2

       Using foreman 0.85.0 from https://github.com/jbox-web/foreman.git (at master@c691ba4)

       Fetching bootsnap 1.5.1

       Installing bootsnap 1.5.1 with native extensions

       Fetching mustermann 1.1.1

       Fetching haml 5.2.1

       Installing mustermann 1.1.1

       Installing haml 5.2.1

       Fetching ruby_parser 3.15.0

       Fetching hashie-forbidden_attributes 0.1.1

       Installing hashie-forbidden_attributes 0.1.1

       Installing ruby_parser 3.15.0

       Fetching sassc 2.4.0

       Installing sassc 2.4.0 with native extensions

       Fetching terminal-table 2.0.0

       Installing terminal-table 2.0.0

       Fetching mini_racer 0.3.1

       Installing mini_racer 0.3.1 with native extensions

       Fetching pastel 0.8.0

       Installing pastel 0.8.0

       Fetching rails-assets-jquery-mousewheel 3.1.13

       Installing rails-assets-jquery-mousewheel 3.1.13

       Fetching sdoc 2.0.3

       Installing sdoc 2.0.3

       Fetching redis-store 1.9.0

       Installing redis-store 1.9.0

       Fetching redis-namespace 1.8.0

       Installing redis-namespace 1.8.0

       Fetching sidekiq 6.1.2

       Installing sidekiq 6.1.2

       Fetching strings 0.2.0

       Installing strings 0.2.0

       Fetching turbolinks 5.2.1

       Installing turbolinks 5.2.1

       Fetching activesupport 5.2.4.4

       Installing activesupport 5.2.4.4

       Fetching dry-configurable 0.11.6

       Installing dry-configurable 0.11.6

       Fetching dry-logic 1.0.8

       Installing dry-logic 1.0.8

       Fetching loofah 2.8.0

       Installing loofah 2.8.0

       Fetching mustermann-grape 1.0.1

       Installing mustermann-grape 1.0.1

       Fetching html2haml 2.2.0

       Installing html2haml 2.2.0

       Fetching rails-assets-datetimepicker 2.5.20

       Installing rails-assets-datetimepicker 2.5.20

       Fetching redis-rack 2.1.3

       Installing redis-rack 2.1.3

       Fetching tty-table 0.12.0

       Installing tty-table 0.12.0

       Fetching rails-dom-testing 2.0.3

       Installing rails-dom-testing 2.0.3

       Fetching globalid 0.4.2

       Installing globalid 0.4.2

       Fetching activemodel 5.2.4.4

       Installing activemodel 5.2.4.4

       Fetching groupdate 5.2.1

       Installing groupdate 5.2.1

       Fetching redis-activesupport 5.2.0

       Installing redis-activesupport 5.2.0

       Fetching simple-navigation 4.1.0

       Installing simple-navigation 4.1.0

       Fetching dry-container 0.7.2

       Installing dry-container 0.7.2

       Fetching rails-html-sanitizer 1.3.0

       Installing rails-html-sanitizer 1.3.0

       Fetching activejob 5.2.4.4

       Installing activejob 5.2.4.4

       Fetching activerecord 5.2.4.4

       Installing activerecord 5.2.4.4

       Fetching simple_navigation_bootstrap 1.3.0

       Installing simple_navigation_bootstrap 1.3.0

       Fetching dry-types 1.4.0

       Installing dry-types 1.4.0

       Fetching actionview 5.2.4.4

       Installing actionview 5.2.4.4

       Fetching acts_as_list 1.0.2

       Installing acts_as_list 1.0.2

       Fetching after_commit_everywhere 0.1.5

       Installing after_commit_everywhere 0.1.5

       Fetching kaminari-activerecord 1.2.1

       Installing kaminari-activerecord 1.2.1

       Fetching grape 1.5.1

       Installing grape 1.5.1

       Fetching actionpack 5.2.4.4

       Installing actionpack 5.2.4.4

       Fetching kaminari-actionview 1.2.1

       Installing kaminari-actionview 1.2.1

       Fetching record_tag_helper 1.0.1

       Installing record_tag_helper 1.0.1

       Fetching actioncable 5.2.4.4

       Installing actioncable 5.2.4.4

       Fetching actionmailer 5.2.4.4

       Installing actionmailer 5.2.4.4

       Fetching activestorage 5.2.4.4

       Installing activestorage 5.2.4.4

       Fetching railties 5.2.4.4

       Installing railties 5.2.4.4

       Fetching sprockets-rails 3.2.2

       Installing sprockets-rails 3.2.2

       Fetching redis-actionpack 5.2.0

       Installing redis-actionpack 5.2.0

       Fetching kaminari 1.2.1

       Installing kaminari 1.2.1

       Fetching exception_notification 4.4.3

       Installing exception_notification 4.4.3

       Fetching ajax-datatables-rails 1.2.0

       Installing ajax-datatables-rails 1.2.0

       Fetching bootstrap-slider-rails 9.8.0

       Installing bootstrap-slider-rails 9.8.0

       Fetching codemirror-rails 5.16.0

       Installing codemirror-rails 5.16.0

       Fetching coffee-rails 5.0.0

       Installing coffee-rails 5.0.0

       Fetching responders 3.0.1

       Installing responders 3.0.1

       Fetching dotenv-rails 2.7.6

       Installing dotenv-rails 2.7.6

       Fetching font-awesome-rails 4.7.0.5

       Installing font-awesome-rails 4.7.0.5

       Fetching haml-rails 2.0.1

       Installing haml-rails 2.0.1

       Fetching rails-i18n 5.1.3

       Installing rails-i18n 5.1.3

       Fetching jquery-rails 4.4.0

       Installing jquery-rails 4.4.0

       Fetching jquery-ui-rails 6.0.1

       Installing jquery-ui-rails 6.0.1

       Fetching zeroclipboard-rails 0.1.2

       Installing zeroclipboard-rails 0.1.2

       Fetching rails 5.2.4.4

       Installing rails 5.2.4.4

       Fetching redis-rails 5.0.2

       Installing redis-rails 5.0.2

       Fetching devise 4.7.3

       Installing devise 4.7.3

       Fetching i18n-tasks 0.9.32

       Installing i18n-tasks 0.9.32

       Using action_form 1.3.0 from https://github.com/jbox-web/action_form.git (at master@f5d146b)

       Using active_use_case 1.3.0 from https://github.com/jbox-web/active_use_case.git (at 1.3.0@c124ee9)

       Using async_model 1.0.0 from https://github.com/jbox-web/async_model.git (at master@97da711)

       Fetching rails_bootstrap_navbar 3.0.0

       Fetching smart_listing 1.2.3

       Fetching bootstrap-sass 3.4.1

       Installing smart_listing 1.2.3

       Installing rails_bootstrap_navbar 3.0.0

       Fetching font-awesome-sass 5.15.1

       Installing bootstrap-sass 3.4.1

       Fetching sassc-rails 2.1.2

       Installing sassc-rails 2.1.2

       Installing font-awesome-sass 5.15.1

       Fetching sass-rails 6.0.0

       Installing sass-rails 6.0.0

       Bundle complete! 96 Gemfile dependencies, 173 gems now installed.

       Gems in the groups development and test were not installed.

       Bundled gems are installed into `./vendor/bundle`

       Post-install message from i18n:

       

       HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.

       But that may break your application.

       

       If you are upgrading your Rails application from an older version of Rails:

       

       Please check your Rails app for 'config.i18n.fallbacks = true'.

       If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be

       'config.i18n.fallbacks = [I18n.default_locale]'.

       If not, fallbacks will be broken in your app by I18n 1.1.x.

       

       If you are starting a NEW Rails application, you can ignore this notice.

       

       For more info see:

       https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

       

       Post-install message from i18n-tasks:

       # Install default configuration:

       cp $(bundle exec i18n-tasks gem-path)/templates/config/i18n-tasks.yml config/

       # Add an RSpec for missing and unused keys:

       cp $(bundle exec i18n-tasks gem-path)/templates/rspec/i18n_spec.rb spec/

       Bundle completed (308.04s)

       Cleaning up the bundler cache.

-----> Installing node-v12.16.2-linux-x64

-----> Detecting rake tasks

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       rake aborted!

       NoMethodError: undefined method `split' for nil:NilClass

       (erb):37:in `<main>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:66:in `method_missing'

       /tmp/build_49dc4e5c_/config/environments/production.rb:96:in `block in <main>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `instance_eval'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `configure'

       /tmp/build_49dc4e5c_/config/environments/production.rb:17:in `<main>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:608:in `block (2 levels) in <class:Engine>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `each'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `block in <class:Engine>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'

       /tmp/build_49dc4e5c_/config/environment.rb:21:in `<main>'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'

       /tmp/build_49dc4e5c_/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'

       Tasks: TOP => environment

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

please if its possible make dockerfile to your repo or publish on dockerhub.
waiting for your response
finest regards

**Comment by n-rodriguez** [comment]
Add this in your env vars : `WHITE_LISTED_IPS=127.0.0.1`

**Comment by kakamband** [comment]
than one  is fixed but new attention found :
-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       

       Missing required configuration keys: ["APPLICATION_NAME", "DB_ADAPTER", "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASS", "REDIS_HOST", "REDIS_PORT", "REDIS_DB", "MAIL_FROM", "LOG_LEVEL", "ACCESS_URL", "FAYE_SECRET", "AUTHENTICATION_SERVER", "AUTHENTICATION_TOKEN", "ACCESS_DOMAIN_NAME", "DOCKER_REGISTRY", "APPLICATIONS_CLONES_DIR", "APPLICATIONS_REPOS_DIR", "APPLICATIONS_DATAS_DIR", "SCRIPTS_PATH", "SESSION_TIMEOUT", "MAIL_ON_APPLICATION_ERROR"]

 !

 !     Precompiling assets failed.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

**### please if its possible make heroku.yml or app.json & make deploy to heroku button for this paas project .
waiting for your response**
